---
- hosts: webservers
  vars: {}
  ansible_ssh_user: vagrant
  ansible_ssh_pass: vagrant # just for demonstration purposes!
  become: True
  become_user: root

  tasks: []

  roles:
    - { role: common, tags: ['common'] }
